name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: git config
      run: git config --global user.email "vishwasm@devtools.in" && git config --global user.name "vishwasnm2"
    - name : git add and commit 
      run : git add . && git commit -m "commit msg added"
    - name: remote name
      run: git remote -v >> new.txt
    - name : read
      run : cat new.txt
    - name : git push 
      run : git push https://vishwasnm2:${{secrets.GITHUBPAT}}@github.com/vishwasnm2/DevOpsClassCodes HEAD:master
    - name : change directory
      run : cd /home
    - name : update
      run : sudo apt-get update
    - name : install docker
      run : sudo apt-get install docker
    - name : test
      run : sudo docker run hello-world
    
  
      
